In [1]:
import numpy as np

# Problem 1
>The formula used in this problem would be<br>
$c_{i, j}=\sum^{2}_{0}a_{i, k}b_{k, j}$<br>
For example, the resulting matrix would have a shape of (3, 3) due to the <b>3</b> rows of matrix A and <b>3</b> rows of matrix B. The first index on row 0 and column 0 would be calculated as A\[0\]\[0\] * B\[0\]\[0\] + A\[0\]\[1\] * B.\[1\]\[0\]  + A\[0\]\[2\] * B\[2\]\[0\].<br>
The result matrix would be:<br>
$$\begin{bmatrix} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48 \end{bmatrix}$$

# Problem 2

In [9]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
matrix_product = a_ndarray @ b_ndarray
matrix_product_2 = np.matmul(a_ndarray, b_ndarray)
matrix_product_3 = np.dot(a_ndarray, b_ndarray)
print(matrix_product)
print(matrix_product_2)
print(matrix_product_3)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# Problem 3

In [14]:
matrix_problem_3 = np.zeros((len(a_ndarray), len(a_ndarray[0])))
for i in range(len(a_ndarray)):
    for j in range(len(a_ndarray[0])):
        matrix_problem_3[i][j] = np.sum(a_ndarray[i] * b_ndarray.T[j])
print(matrix_problem_3)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# Problem 4

In [19]:
def matrix_mul(A, B):
    result = np.zeros((A.shape[0], B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            result[i][j] = np.sum(A[i] * B.T[j])
    return result
print(matrix_mul(a_ndarray, b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# Problem 5

In [21]:
def matrix_mul_with_error_checking(A, B):
    if A.shape[0] == B.shape[1]:
        result = np.zeros((A.shape[0], B.shape[1]))
        for i in range(A.shape[0]):
            for j in range(B.shape[1]):
                result[i][j] = np.sum(A[i] * B.T[j])
        return result
    else:
        return "Wrong shape!"
result = matrix_mul(a_ndarray, b_ndarray)
print(result)

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# Problem 6

In [22]:
if type(result) != str:
    print(result.T)

[[  6.  12. -18.]
 [ 29.  52. -51.]
 [-20.  38. -48.]]
