In [1]:
import warnings
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("Mean:", scaler.mean_)
print("Variance:", scaler.var_)
X_std = scaler.transform(X)

Mean: [4.86 3.31 1.45 0.22]
Variance: [0.0764 0.0849 0.0105 0.0056]


# Problem 1

<blockquote>
    <ul>
        <li><b>Pandas</b>: DataFrame.</li>
        <li><b>matplotlib</b>: pyplot, colors.</li>
        <li><b>sklearn</b>: datasets, preprocessing, metrics.</li>
    </ul>
</blockquote>

In [2]:
print("Mean: {}".format(scaler.mean_))
print("Variance : {}".format(scaler.var_))

Mean: [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]


# Problem 2

<blockquote>
In <b>numpy</b> I have used method such as sum(), max(), min(), array(), copy() and instance variables such as dtype, reshape, shape, mean, var.</li>
</blockquote>

# Problem 3

In [3]:
class ScratchStandardScaler():
    """
    Class for standardization 
    Attributes
    ----------
    mean_ : ndarray, shape(n_features,)
    var_ : ndarray, shape(n_features,)
    """
    def fit(self, X):
        """
        Calculate the mean and standard deviation for standardization
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
        """
        self.mean_ = np.mean(X, axis = 0)
        self.var_ = np.var(X, axis = 0)
    def transform(self, X):
        """
        Standardize using the value obtained in fit
        Parameters
        ----------
        X : ndarray, shape (n_samples, n_features)
        Returns
        ----------
        X_scaled : ndarray, shape (n_samples, n_features)
        """
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [4]:
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Mean : {}".format(scratch_scaler.mean_))
print("Var : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Var : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [5]:
class ExampleClass():
    """
    A simple class for explanation
    Parameters
    ----------
    value : float or int
        initial value
    Attributes
    ----------
    value : float or int
        Calculation result
    """
    def __init__(self, value):
        self.value = value
        print("initial value {} was set".format(self.value))
    def add(self, value2):
        """
        Add the received argument to self.value
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

initial value 5 was set
value : 5
value : 8


# Problem 4

In [6]:
class ExampleClass():
    """
    Parameters
    ----------
    value : float or int
    Attributes
    ----------
    value : float or int
    """
    def __init__(self, value):
        if not isinstance(value, (float, int)):
            warnings.warn("Not a number", DeprecationWarning)
        else:
            self.value = value
            print("Initial value {} has been set".format(self.value))
    def add(self, value2):
        """
        Add the received argument to self.value 
        """
        self.value += value2
    def subtract(self, value2):
        """
        Add the received argument to self.value 
        """
        self.value -= value2
    def multiply(self, value2):
        """
        Add the received argument to self.value 
        """
        self.value *= value2
    def divide(self, value2):
        """
        Add the received argument to self.value 
        """
        self.value /= value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.subtract(2)
print("value : {}".format(example.value))
example.multiply(5)
print("value : {}".format(example.value))
example.divide(10)
print("value : {}".format(example.value))
wrong_example = ExampleClass("bruh")

Initial value 5 has been set
value : 5
value : 8
value : 6
value : 30
value : 3.0


<ipython-input-6-c79dd47bdb54>:12: DeprecationWarning: Not a number
  warnings.warn("Not a number", DeprecationWarning)
